keys:
 # Encrypt with PGP and not the SSH key listed in flake.nix:
 # https://github.com/Mic92/sops-nix/issues/297
 - &myself 7098af172f287ddc11270307856556eca9f7b7f1
 # Generate an age key from the host's key:
 #  nix-shell -p ssh-to-age --run 'cat /srv/system/etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'
 # Encrypt a file:
 #  nix-shell -p sops --run "sops hosts/modules/impermanence/backup.yaml"
 # Rekey a file:
 #  nix-shell -p sops --run "sops updatekeys hosts/modules/impermanence/backup.yaml"
 - &acheron age1y6jvnvd0329zev8jt5xy0gms5f2jdn8ak5hjqcfekq79jjnem5hqdrgc63
 - &node-01 age1qv05n6qsv32z2a7krn48njv7jhwzesq0mlsgv3rzddu3r7p5famst79uk5

creation_rules:
 - path_regex: ^hosts/modules/.*\.yaml$
   key_groups:
   - pgp:
      - *myself
     age:
      - *acheron
      - *node-01

 - path_regex: ^hosts/acheron/.*\.yaml$
   key_groups:
   - pgp:
      - *myself
     age:
      - *acheron

 - path_regex: ^hosts/node-01/.*\.yaml$
   key_groups:
   - pgp:
      - *myself
     age:
      - *node-01
