token: ENC[AES256_GCM,data:2q9YPy44Sq9D4aNxppSd+EuGzDvRryOXHUXwdZlG65+jkaypLU8SN4+n1EzHDJdGDiB1gX2K/WePxtRxEdx8sPugDK7dX5Cbo1vuCtpCevTLEBiGGvZASbxNgO11KoGwJXf3,iv:f8bIRiUy8bmLfASxh1LD8YW6zawRwCyvMQi//qxzR3E=,tag:QNwyKe2E8sdteoMLiQ9AEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nxlu55vncq37wp7e4y6cpqzcd6ywh3df3djkct6tm0cv0v5qvynq6svj2u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWemhWNkdJR3ZNSEo1M1Fn
            OWpzTVpEc0I0V3BMT0ZFYmNRTnJ6VG8vT0Y0CjNiNlUrMUtnVk8xZmF5V2ZLMVMy
            ZDUyODJiaWdjWHY4bngzRmJoOXlscTQKLS0tIFNTdTVRR2pzT1h2S0JXMk1mRVJX
            YnlEWGQ1aGVTT1VsSlNKN3FFS2VoUzQKlixErHqJd03sjbZFpFAZtgWKcF2WnaC8
            57d3IgZGwr7o9ze7SoI8qfaLX0sLWf/idrAbsI2nHbayR+xlLbr8dQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w4mj7rlq53pgn0pze2zrwhzk879cenfw3ncyg7985thhth9yadvsgjl8n3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SVcyTnh6a2dremZWTFV6
            N0NYcXczS0Z1WXlLWm9NQW5Zb2JWTnhCY2lrCjlrQVVvQ3hiU0tia3ZZSjFHSGJq
            Mjl2SUNaL3lSeElLbjRzb0puOXJFcEUKLS0tIENLZUJKSStMams5ZDBJdjczK3JI
            VEZtdkxuVmg2M0Q3d0xGMks0ZXh3SFkK6QtAk9JtM1D/SF9F7UD3j5hDp5C1G/Hz
            R3t9CwngrDqu2Vbd015y6pbnHwPEhqaw7jZZa9JO03+vmt2fkdsPcA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age148gs7f8zd5tln4ysngva6naeawpf9vyapecazgsgdft8e49zc3ns2f2wjk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OGh2b3pYM1djRC9GVmcr
            cFBabjBZSW9VSHltL0JIM0ttcTRDNVNSM1hrCmNKWHpLSHA3Z3NJSTVwVGRjTWxY
            M0VzUzhyaFozWW9Nemd3VlJiWFBQRzgKLS0tIFFFR1Z4SUQ0TmcrNERjWTNlbW5X
            VkhHelZpcURud1BDc1krN2VYWmZVbm8K2uPXC34myuhtW3kAYNDhuIKNY0RgPPW+
            fy3V/9fwzoRwgAnFSnbDrg9g59wTrLoYjEluIu51Mku/qdGfCcGIkw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfzal0lh29dlr2dgaxamxuzn5mar6k0nnmpl2kz0hcx2dlsewgnqwvtkvu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncWU2TW9jZ0hWb083SFNj
            ZW1jZnRCbGpCZWttamhrWUp0bSswM0p2RG53ClRXZmhTV0huaVBwZ0RkTzlsbmNk
            Z2ZXMmZaVkVYZ2VJR0V3bzNWZldFNEkKLS0tIDI2cDlxeUJFWXlPaU5xUTl2dEZY
            Ly9ST3dkcGMrZ0tBZ0Q3eE9nVEpXY2sKcorCHWuvmcIWhDShrdBA2QOMKbXkUgBr
            KyqBkT/2ec54u3xJVltjy2zwC7KcqzWLHNlXI7lpFq8KDPQstqFNTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T20:34:06Z"
    mac: ENC[AES256_GCM,data:K2P6qY1UbHXllztsPQfRQSVHYW5dcLQ8/MeJpsqCwLTkM7UD3B5a3zBoAkBGVWJsnHNNNp8RA9GStPDxPNmh0Y/+8WY+AVD2LloQj0K5Mk2JRvFIWKMgK/bBbAf64n8qt0szR+9VcN9jvxGmQ+UZ7ddYVxS7N0qSHxk4KzdwNvA=,iv:AAc5VTXwhqHmvgeDHApvWUINPkBpxXAlEwoQ/2Ogars=,tag:cXxeu2TzFAaEm79Ep/DrRQ==,type:str]
    pgp:
        - created_at: "2023-12-04T20:47:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DLdM+dvDJzsISAQdAdx5kzxlKAny+gg+/SWuL3KQHPxNkqtk3oGQ2d+XHqwcw
            DrienViGyPK80vPO4th6kbopRphuzbHZFtNPjuKsa+WUAN7LNPW2KrEUaSCLqUEU
            0lgBem87RWhoP52vht0qaTOoPNSwAiYufLA7J1V7gR9fZ0oO/WCmBwaroEWDKCpE
            Q1JW8bq8ddhhFBcqe4yZuovjenGduJy9xjmxxomIzuT3/yYJRGEgVdlq
            =iVuD
            -----END PGP MESSAGE-----
          fp: 7098af172f287ddc11270307856556eca9f7b7f1
    unencrypted_suffix: _unencrypted
    version: 3.8.1
