#!/usr/bin/env bash

set -eux
exec >& /tmp/bspwm.log

# basic X configuration
if hash xsetroot; then
  xsetroot -solid '#2b2b2b'
  xsetroot -cursor_name left_ptr
fi

# start pulseaudio
pulseaudio --start & # FIXME: --start daemonize pulseaudio but sometimes it's stuck so background it

# spawn sxhkd
sxhkd &

# create and alternate 10 desktops, starting from 1, on each monitor
# on a two monitors setup, odd desktops would be on first monitor, even on the second
< <(bspc query -M) readarray -t monitors
# rename each default desktop on each monitor
for monitor in "${!monitors[@]}"; do
  bspc monitor "${monitors[$monitor]}" -d $((monitor + 1))
done
# add the remaining desktops, distributed over each monitor
declare -i monitor=0
for desktop in $(seq $((${#monitors[@]} + 1)) 10); do
  bspc monitor "${monitors[$monitor]}" -a $desktop
  monitor=$(((monitor + 1) % ${#monitors[@]}))
done

# basic bspwm configuration
bspc config border_width 1
bspc config window_gap 10
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config click_to_focus true # 0.9.3 deprecated, now a button name
bspc config focus_follows_pointer true

# bspwm style configuration (compton may be used to tweak it more)
bspc config normal_border_color '#2b2b2b' # unfocused window
bspc config active_border_color '#2b2b2b' # focused window on unfocused monitor
bspc config focused_border_color '#8fb28f'
bspc config presel_feedback_color '#f0dfaf'
