root: ENC[AES256_GCM,data:/hiOLtsiyCUxw85UV43HwRbbztyjTFLQox6UnxGX8wtH/CsUoBX12jKpadCFzzua+5Az4qI0N2ZSPawM5WrY/6fe+cZO2RxrzA==,iv:qwGM6+YoYtMs5/CcCJaZPqutTuR3km3dbTsKxLUElII=,tag:3PlkOyd138DPMlL5aUMacA==,type:str]
meshPrivateKey: ENC[AES256_GCM,data:NT30RYosA2lVDzUBrmFEEoIX38iIcrhow7NyrIgBwXf3M5Qya/1wFxpUSoc=,iv:Wa2hR3gWrAQWG/n5FYnAAZc9rvRXUMpJKFj+CU9u1lc=,tag:SXVasWzIhez5e6G1aP+tkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lfzal0lh29dlr2dgaxamxuzn5mar6k0nnmpl2kz0hcx2dlsewgnqwvtkvu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMUxRQThyQTJOQlRyUzhN
            NWZyM2FVT0lDZHQ4OWpPKzFMZ0RkTHVjTzA4Ckh0bmVidlJWaktpSUx0NGlDQ3dk
            WS9qem10SnhjN1czNHlXVlc2cWNlT0kKLS0tIHAzWm94aEJEb1FDRSsrWmRJNVpo
            RjNQN3VHN1ZwcjA0NzVsOFdsZStQak0KoFR8kJnux0Ctf+aNmtM9tKom39dueVHS
            LP0Iq+4dBM+EbLsKX16nA8mI0uoXoIwX8yagN7wvDb9AQIg+3tFUfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-02T13:01:43Z"
    mac: ENC[AES256_GCM,data:9AuWr4GWm/u0JcJ6N+sjnH5tUchkj7H6jysIMXQbbjIrkZuoDYrb6nkY5XpXW7dWkTMuHr5WeQWrAGGfJfpy07Nt+ckb+ag9/pVtMJG1CqDJYjcWkbO3SvgKAk4ckW+xcXy85PfPLoIWdgKpY8sDjVQMY7G5/Yz8bF+fUmByWNY=,iv:twnWUBerWb1Q+4A19uJ+PQ6PYp0XkQ5KtE7wpYoEzt0=,tag:Zjmf6561IABBeGazkD3R9Q==,type:str]
    pgp:
        - created_at: "2023-11-26T16:12:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DLdM+dvDJzsISAQdAHn61XLZvr+a2vPu/cF2nvOe15d366Et27ZOnqVXayiMw
            Ksdp7nRlQ5Z9kKd/ilhJMfoaqU4I5kpjtj2huTqhTQ0/pFW+mfOeEwTpikIiKY0t
            0lgBiJ8MlB10AbzX0hFqvw8+KhRXkflxV2la8jxbTb3c+coqglTbXfkG6AC2M2OP
            BW3twoTM9+2tBLWZzqMXzqjt9Jk6fdppM8R8BFdKBLJgxHpDEiu43eNu
            =cy+z
            -----END PGP MESSAGE-----
          fp: 7098af172f287ddc11270307856556eca9f7b7f1
    unencrypted_suffix: _unencrypted
    version: 3.8.1
